AOS Fog of War: FischlWorks_FogWar.csFogWar Class Reference
FischlWorks_FogWar.csFogWar Class Reference
The non-static high-level monobehaviour interface of the AOS Fog of War module.
Classes
class FogRevealer
class LevelColumn
class LevelData
Public Member Functions
void AddFogRevealer (FogRevealer fogRevealer)
Adds a new FogRevealer instance to the list.
bool CheckLevelGridRange (Vector2Int levelCoordinates)
Checks if the given level coordinates are within level dimension range.
bool CheckVisibility (Vector3 worldCoordinates, int additionalRadius)
Checks if the given pair of world coordinates and additionalRadius is visible by FogRevealers.
bool CheckWorldGridRange (Vector3 worldCoordinates)
Checks if the given world coordinates are within level dimension range.
Vector2Int GetUnitVector (Vector3 worldCoordinates)
Converts "pure" world coordinates into unit world coordinates.
int GetUnitX (float xValue)
Converts world coordinate to unit world coordinates.
int GetUnitY (float yValue)
Converts world coordinate to unit world coordinates.
Vector3 GetWorldVector (Vector2Int worldCoordinates)
Converts level coordinates into world coordinates.
float GetWorldX (int xValue)
Converts level coordinate to corresponding unit world coordinates.
float GetWorldY (int yValue)
Converts level coordinate to corresponding unit world coordinates.
Vector2Int WorldToLevel (Vector3 worldCoordinates)
Converts unit (divided by unitScale, then rounded) world coordinates to level coordinates.
Properties
float _UnitScale [get]
LevelData levelData = new LevelData() [get]
Shadowcaster shadowcaster = new Shadowcaster() [get]
Detailed Description
The non-static high-level monobehaviour interface of the AOS Fog of War module.
This class holds serialized data for various configuration properties,
and is resposible for scanning / saving / loading the LevelData object.
The class handles the update frequency of the fog, plus some shader businesses.
Various public interfaces related to FogRevealer's FOV are also available.
Member Function Documentation
AddFogRevealer()
void FischlWorks_FogWar.csFogWar.AddFogRevealer (FogRevealer fogRevealer) inline
Adds a new FogRevealer instance to the list.
        {
            fogRevealers.Add(fogRevealer);
        }
CheckLevelGridRange()
bool FischlWorks_FogWar.csFogWar.CheckLevelGridRange (Vector2Int levelCoordinates) inline
Checks if the given level coordinates are within level dimension range.
        {
            bool result =
                levelCoordinates.x >= 0 &&
                levelCoordinates.x < levelData.levelDimensionX &&
                levelCoordinates.y >= 0 &&
                levelCoordinates.y < levelData.levelDimensionY;
            if (result == false && LogOutOfRange == true)
            {
                Debug.LogFormat("Level coordinates \"{0}\" is out of grid range", levelCoordinates);
            }
            return result;
        }
Referenced by FischlWorks_FogWar.csFogWar.CheckVisibility(), and FischlWorks_FogWar.csFogWar.CheckWorldGridRange().
CheckVisibility()
bool FischlWorks_FogWar.csFogWar.CheckVisibility (Vector3 worldCoordinates, int additionalRadius) inline
Checks if the given pair of world coordinates and additionalRadius is visible by FogRevealers.
        {
            Vector2Int levelCoordinates = WorldToLevel(worldCoordinates);
            if (additionalRadius == 0)
            {
                return shadowcaster.fogField[levelCoordinates.x][levelCoordinates.y] ==
                    Shadowcaster.LevelColumn.ETileVisibility.Revealed;
            }
            int scanResult = 0;
            for (int xIterator = -1; xIterator < additionalRadius + 1; xIterator++)
            {
                for (int yIterator = -1; yIterator < additionalRadius + 1; yIterator++)
                {
                    if (CheckLevelGridRange(new Vector2Int(
                        levelCoordinates.x + xIterator,
                        levelCoordinates.y + yIterator)) == false)
                    {
                        scanResult = 0;
                        break;
                    }
                    scanResult += Convert.ToInt32(
                        shadowcaster.fogField[levelCoordinates.x + xIterator][levelCoordinates.y + yIterator] ==
                        Shadowcaster.LevelColumn.ETileVisibility.Revealed);
                }
            }
            if (scanResult > 0)
            {
                return true;
            }
            return false;
        }
CheckWorldGridRange()
bool FischlWorks_FogWar.csFogWar.CheckWorldGridRange (Vector3 worldCoordinates) inline
Checks if the given world coordinates are within level dimension range.
        {
            Vector2Int levelCoordinates = WorldToLevel(worldCoordinates);
            return CheckLevelGridRange(levelCoordinates);
        }
GetUnitVector()
Vector2Int FischlWorks_FogWar.csFogWar.GetUnitVector (Vector3 worldCoordinates) inline
Converts "pure" world coordinates into unit world coordinates.
        {
            return new Vector2Int(GetUnitX(worldCoordinates.x), GetUnitY(worldCoordinates.z));
        }
Referenced by FischlWorks_FogWar.csFogWar.WorldToLevel().
GetUnitX()
int FischlWorks_FogWar.csFogWar.GetUnitX (float xValue) inline
Converts world coordinate to unit world coordinates.
        {
            return Mathf.RoundToInt((xValue - levelMidPoint.position.x) / unitScale);
        }
Referenced by FischlWorks_FogWar.csFogWar.FogRevealer.GetCurrentLevelCoordinates(), and FischlWorks_FogWar.csFogWar.GetUnitVector().
GetUnitY()
int FischlWorks_FogWar.csFogWar.GetUnitY (float yValue) inline
Converts world coordinate to unit world coordinates.
        {
            return Mathf.RoundToInt((yValue - levelMidPoint.position.z) / unitScale);
        }
Referenced by FischlWorks_FogWar.csFogWar.FogRevealer.GetCurrentLevelCoordinates(), and FischlWorks_FogWar.csFogWar.GetUnitVector().
GetWorldVector()
Vector3 FischlWorks_FogWar.csFogWar.GetWorldVector (Vector2Int worldCoordinates) inline
Converts level coordinates into world coordinates.
        {
            return new Vector3(
                GetWorldX(worldCoordinates.x + (levelDimensionX / 2)),
                0,
                GetWorldY(worldCoordinates.y + (levelDimensionY / 2)));
        }
GetWorldX()
float FischlWorks_FogWar.csFogWar.GetWorldX (int xValue) inline
Converts level coordinate to corresponding unit world coordinates.
        {
            if (levelData.levelDimensionX % 2 == 0)
            {
                return (levelMidPoint.position.x - ((levelDimensionX / 2.0f) - xValue) * unitScale);
            }
            return (levelMidPoint.position.x - ((levelDimensionX / 2.0f) - (xValue + 0.5f)) * unitScale);
        }
Referenced by FischlWorks_FogWar.csFogWar.GetWorldVector().
GetWorldY()
float FischlWorks_FogWar.csFogWar.GetWorldY (int yValue) inline
Converts level coordinate to corresponding unit world coordinates.
        {
            if (levelData.levelDimensionY % 2 == 0)
            {
                return (levelMidPoint.position.z - ((levelDimensionY / 2.0f) - yValue) * unitScale);
            }
            return (levelMidPoint.position.z - ((levelDimensionY / 2.0f) - (yValue + 0.5f)) * unitScale);
        }
Referenced by FischlWorks_FogWar.csFogWar.GetWorldVector().
WorldToLevel()
Vector2Int FischlWorks_FogWar.csFogWar.WorldToLevel (Vector3 worldCoordinates) inline
Converts unit (divided by unitScale, then rounded) world coordinates to level coordinates.
        {
            Vector2Int unitWorldCoordinates = GetUnitVector(worldCoordinates);
            return new Vector2Int(
                unitWorldCoordinates.x + (levelDimensionX / 2),
                unitWorldCoordinates.y + (levelDimensionY / 2));
        }
Referenced by FischlWorks_FogWar.csFogWar.CheckVisibility(), and FischlWorks_FogWar.csFogWar.CheckWorldGridRange().
Property Documentation
_UnitScale
float FischlWorks_FogWar.csFogWar._UnitScale get
levelData
LevelData FischlWorks_FogWar.csFogWar.levelData = new LevelData() get
{ get; private set; } = new LevelData();
Referenced by FischlWorks_FogWar.csFogWar.CheckLevelGridRange(), FischlWorks_FogWar.csFogWar.GetWorldX(), FischlWorks_FogWar.csFogWar.GetWorldY(), and FischlWorks_FogWar.Shadowcaster.Initialize().
shadowcaster
Shadowcaster FischlWorks_FogWar.csFogWar.shadowcaster = new Shadowcaster() get
{ get; private set; } = new Shadowcaster();
Referenced by FischlWorks_FogWar.csFogWar.CheckVisibility().
The documentation for this class was generated from the following file:
C:/Users/keith/Desktop/HomebrewFogofwar/Assets/AOSFogWar/csFogWar.cs